name: basic
version: 0.2.1
date: 'date_id'
ncpu: '4'
verbose: '-vv'
prj_workspace:
  expdir: 
  jobdir: 
  reldir: 
  rstdir: 
  logdir: 
main_inputs:
  indir: ''
  outdir: ''
  species: Homo sapiens
databases:
  labeldecoy: INV_
  catid: 202010
  catdb: dbs\202010\human_202010_sw.categories.tsv
datfiles:
  - type: main_inputs
    file: 
  - type: databases
    file: 
  - type: identification
    file: 
  - type: stats_quantification
    file: 
  - type: integration
    file: 
  - type: reports
    file: 
