name: basic/w_catfile
version: ''
date: ''
ncpu: ''
verbose: '-vv'
prj_workspace:
  expdir: 
  jobdir: 
  reldir: 
  rstdir: 
  logdir: 
main_inputs:
  indir: ''
  outdir: ''
databases:
  species: ''
  labeldecoy: ''
  catfile: ''
  dbfile: ''
datfiles:
  - type: main_inputs
    file: 
  - type: databases
    file: 
  - type: identification
    file: 
  - type: stats_quantification
    file: 
  - type: integration
    file: 
  - type: reports
    file: 
