name: basic/w_uniprot
version: ''
date: ''
ncpu: ''
verbose: '-vv'
prj_workspace:
  expdir: 
  jobdir: 
  reldir: 
  rstdir: 
  logdir: 
main_inputs:
  indir: ''
  outdir: ''
databases:
  species: ''
  labeldecoy: ''
  catid: ''
  catdbs: ''
datfiles:
  - type: main_inputs
    file: 
  - type: databases
    file: 
  - type: identification
    file: 
  - type: stats_quantification
    file: 
  - type: integration
    file: 
  - type: reports
    file: 
