name: ptm
version: 0.2.8
date: 'date_id'
ncpu: '4'
verbose: '-vv'
prj_workspace:
  expdir: 
  jobdir: 
  reldir: 
  rstdir: 
  logdir: 
main_inputs:
  __MAIN_INPUTS_OUTDIR__: ''
  __MAIN_INPUTS_INDIR__: ''
  __MAIN_INPUTS_PSMFILE__: ''
  __MAIN_INPUTS_PDMFILE__: ''
databases:
  species: 'Mus musculus'
  catid: '202103'
  catdbs: ''
datfiles:
  - type: main_inputs
    file: 
  - type: databases
    file: 
  - type: identification
    file: 
  - type: stats_quantification
    file: 
  - type: integration
    file: 
  - type: reports
    file: 
