name: ptm
version: 0.2.11
date: 'date_id'
ncpu: '4'
verbose: '-vv'
prj_workspace:
  expdir: 
  jobdir: 
  reldir: 
  rstdir: 
  logdir: 
main_inputs:
  __OUTDIR__: ''
  __INDIR__: ''
  __PSMFILE__: ''
  __PDMFILE__: ''
databases:
  __DBID__: ''
  __SPECIES__: ''
  __CATDB__: ''
datfiles:
  - type: main_inputs
    file: 
  - type: databases
    file: 
  - type: identification
    file: 
  - type: stats_quantification
    file: 
  - type: integration
    file: 
  - type: reports
    file: 
