name: basic
version: 0.2.10
date: 'date_id'
ncpu: '4'
verbose: '-vv'
prj_workspace:
  expdir: 
  jobdir: 
  reldir: 
  rstdir: 
  logdir: 
main_inputs:
  __MAIN_INPUTS_OUTDIR__: ''
  __MAIN_INPUTS_INDIR__: ''
databases:
  __MAIN_INPUTS_DBID__: ''
  __MAIN_INPUTS_SPECIES__: ''
  __MAIN_INPUTS_CATDB__: ''
datfiles:
  - type: main_inputs
    file: 
  - type: databases
    file: 
  - type: identification
    file: 
  - type: stats_quantification
    file: 
  - type: integration
    file: 
  - type: reports
    file: 
